name: x86-64 Pull and Save Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest,ubuntu:latest'

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "${image}" --platform "linux/amd64"
          image_name="${image//\//_}"
          docker save "${image}" -o "${image_name}-amd64.tar"
        done

    - name: Compress each TAR file
      run: |
        for tar_file in *-amd64.tar; do
          tar -czf "${tar_file%.tar}.tar.gz" "$tar_file"
        done

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar
        path: '*.tar.gz'
        retention-days: 90

    - name: Clean up intermediate files
      run: |
        rm *-amd64.tar
